### ISSUE TITLE
Can't trace image using CLI, but can on site demo - thread main panicked at

### ISSUE THREAD

**Issue by Shmacked** [visioncortex/vtracer#40]
I can't trace the image using the CLI, but I can on your site demo (though the black and white color scheme is flipped). I am running version 0.4.0 and, from I can gather, this shouldn't be fixed with 0.5.0.

The traceback is:
```
thread 'main' panicked at 'range end index 73543680 out of range for slice of length 27125760', C:\Users\Webmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.23.11\./src\codecs\bmp\decoder.rs:309:41
stack backtrace:
   0:     0x7ff73ed66a79 - <unknown>
   1:     0x7ff73ed7cf4b - <unknown>
   2:     0x7ff73ed63554 - <unknown>
   3:     0x7ff73ed69b1b - <unknown>
   4:     0x7ff73ed69759 - <unknown>
   5:     0x7ff73ed6a2ff - <unknown>
   6:     0x7ff73ed69e65 - <unknown>
   7:     0x7ff73ed6732f - <unknown>
   8:     0x7ff73ed69e19 - <unknown>
   9:     0x7ff73ed7acb0 - <unknown>
  10:     0x7ff73ed7ef27 - <unknown>
  11:     0x7ff73ec71eb7 - <unknown>
  12:     0x7ff73ec79596 - <unknown>
  13:     0x7ff73ec79fb7 - <unknown>
  14:     0x7ff73ec555d7 - <unknown>
  15:     0x7ff73ec241d7 - <unknown>
  16:     0x7ff73ec1e281 - <unknown>
  17:     0x7ff73ec16e2b - <unknown>
  18:     0x7ff73ec15adc - <unknown>
  19:     0x7ff73ec110b5 - <unknown>
  20:     0x7ff73ec111c6 - <unknown>
  21:     0x7ff73ec111dc - <unknown>
  22:     0x7ff73ed6a616 - <unknown>
  23:     0x7ff73ec111b7 - <unknown>
  24:     0x7ff73ed84544 - <unknown>
  25:     0x7ff83a1c7614 - BaseThreadInitThunk
  26:     0x7ff83b5226a1 - RtlUserThreadStart
```

The image for recreating is attached. I want to use the black and white mode for tracing, and obviously, this is a png with rgba colors, so I use python PIL to convert it ->
```
from PIL import Image
Image.open("test3.png").convert("1").save("test3.bmp")
```

This should give you a bmp to run through VTracer. I use the command like so, to produce an svg, to which the error is thrown:
```
vtracer --colormode bw -i test3.bmp -o test3.svg
```

While I am here, your site demo inverts the color scheme - is there a command to do that? I checked the help menu and see none, so I just wanted to make sure that wasn't overlooked in the help menu.

Quick note: I download 0.5.0 to give it a quick test and the results were the same; the backtrace might be different so I am posting it here as well:
```
thread 'main' panicked at 'range end index 73543680 out of range for slice of length 27125760', C:\Users\Webmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.23.14\./src\codecs\bmp\decoder.rs:309:41
stack backtrace:
   0:     0x7ff63ecd6c82 - <unknown>
   1:     0x7ff63ecef30b - <unknown>
   2:     0x7ff63ecd378a - <unknown>
   3:     0x7ff63ecd8e94 - <unknown>
   4:     0x7ff63ecd8aca - <unknown>
   5:     0x7ff63ecd9681 - <unknown>
   6:     0x7ff63ecd958d - <unknown>
   7:     0x7ff63ecd76af - <unknown>
   8:     0x7ff63ecd9250 - <unknown>
   9:     0x7ff63ecfc575 - <unknown>
  10:     0x7ff63ecf1b27 - <unknown>
  11:     0x7ff63ecfc719 - <unknown>
  12:     0x7ff63ecf7742 - <unknown>
  13:     0x7ff63ec071b6 - <unknown>
  14:     0x7ff63ebb2ff3 - <unknown>
  15:     0x7ff63ebb524a - <unknown>
  16:     0x7ff63ebb1014 - <unknown>
  17:     0x7ff63eba74ed - <unknown>
  18:     0x7ff63eba5a95 - <unknown>
  19:     0x7ff63eba10ba - <unknown>
  20:     0x7ff63eba11f6 - <unknown>
  21:     0x7ff63eba120c - <unknown>
  22:     0x7ff63ecce56e - <unknown>
  23:     0x7ff63eba11dc - <unknown>
  24:     0x7ff63ecf5f54 - <unknown>
  25:     0x7ff83a1c7614 - BaseThreadInitThunk
  26:     0x7ff83b5226a1 - RtlUserThreadStart
```

![test3](https://user-images.githubusercontent.com/19714390/221377229-501badf3-0724-4d81-8cda-557c4134e5b6.png)

**Comment by tyt2y3** [comment]
This is strange, but since it works in the web demo, I suggest you to convert / flatten the png again to get rid of any potential encoding issue, like an alpha channel.

The web demo also intentionally flips black & white, to make it look like it has done something.

**Comment by Shmacked** [comment]
Well, I do. I convert it to a black and white bitmap image using python and trace it in `bw` mode ->

```
from PIL import Image
Image.open("test3.png").convert("1").save("test3.bmp")
```

Nice to know about the web demo; that's what I figured. I have no trouble tracing the same image, but scaled down proportionally.
